### ISSUE TITLE
Add configuration settings for mininum, maximum, and default height.

### ISSUE THREAD

**Issue by Alexia** [Alexia/mediawiki-embedvideo#11]
Add configuration settings for mininum, maximum, and default height.

The setWidth() and setHeight() functions may need an extra parameter to allow overriding these in case of calculating based on the service's provided ratio.

**Comment by kghbln** [comment]
If I look at [the docu](https://www.mediawiki.org/wiki/Extension:EmbedVideo#Configuration_Settings) it looks like this is now implemented. Cool! So this issue could be closed. What I do not know is which version introduced these configuration parameters.

**Comment by Alexia** [comment]
Looks like I did width for the 2.1 made fixes in the 2.1.1 release.  I never really came up with a good way to set height independently and have it be user friendly.  As well, since width automatically sets the height proportionally, it does not really make sense to have be implemented.  If the consensus is that being able to set height independently is not needed then this issue can be closed.

https://github.com/Alexia/mediawiki-embedvideo/commit/dab090bccc897151e823e1f420441a65702ba240

**Comment by kghbln** [comment]
Ah, this was about height too. Sorry for this. Well, I personally do not see the need to set height independently.

**Comment by Alexia** [comment]
With that and considering that no one has made a pull request for it and I have not made time to work on it I will close this issue until it comes up again.
