### ISSUE TITLE
White screen of death 

### ISSUE THREAD

**Issue by nderambure** [Alexia/mediawiki-embedvideo#29]
Hi,

I've a mediawiki 1.23.8 installed on a classic debian and EmbedVideo v2.1.4 which works fine.
But if I update to the last version (last commit at this moment), I've got a blank screen on any page.
Did you test this version against the 1.23.8 ?

Thx !

**Comment by Alexia** [comment]
Are you running PHP 5.4 or higher?  If not use the older version that supports PHP 5.3.

https://github.com/Alexia/mediawiki-embedvideo/archive/v2.2.1.zip

**Comment by nderambure** [comment]
Hey, thx for quick answer.
Yep, I'm using PHP 5.3, that's why it fails...
Thx for pointing !
