### ISSUE TITLE
NicoVideo video ID issue

### ISSUE THREAD

**Issue by KyoriAsh** [Alexia/mediawiki-embedvideo#34]
I would like to raise an issue regarding NicoVideo video id problem. As of the source code, the video id is "locked" with smxxxxxx where xxxxx are represented with number. However, NicoVideo video id DOES contains other than "smxxxxxxx" such as "nmxxxxxxxx" and "soxxxxxxxx". You may refer to my user page in Kancollewiki zh: http://zh.kcwiki.moe/wiki/User:KyoriAsh

My suggestion is:

'url_regex'		=> [
				'#nicovideo\.jp/watch/(sm[\d]+)#is'
			],
			'id_regex'		=> [
				'#^(sm[\d]+)$#is'
			]

change to

'url_regex'		=> [
				'#nicovideo\.jp/watch/([A-Za-z]{2}\d+)#is'
			],
			'id_regex'		=> [
				'#^([A-Za-z]{2}\d+)$#is'
			]

so that it will cover those aforementioned video id.

**Comment by Alexia** [comment]
I am on bugs this week so I am putting this into my queue to fix it.

**Comment by Alexia** [comment]
I tested the issue and also found they now also use pure numeric video IDs.  I updated the regex and made a new release to fix the issue.

https://github.com/Alexia/mediawiki-embedvideo/releases/tag/v2.2.6
