### ISSUE TITLE
PHP 5.4 minimum requirement, MediaWiki supports 5.3.3

### ISSUE THREAD

**Issue by MarkTraceur** [Alexia/mediawiki-embedvideo#36]
Small problem here, nothing too huge. We had someone come into #wikimedia-multimedia today to ask about short array syntax. At first I thought he had written new code for the extension, and told him that he should use array() instead, but I later found out that you all had a PHP 5.4 requirement, where MediaWiki only requires 5.3.3.

Is there anything besides the short array syntax that isn't compatible? Is it possible to just move back to long array syntax?

**Comment by Alexia** [comment]
I believe that is minimally the main reason.  Generally when someone asks about this I recommend that they upgrade to 5.4 as there are no incompatible changes in that version of PHP that would affect MySQL.  As well, PHP 5.3 has been long marked end of life and no longer receives security patches.

I just pushed up an unfinished and untested 5.3 compatible branch.  I might be able to finish it later today.
https://github.com/Alexia/mediawiki-embedvideo/tree/compat

**Comment by Alexia** [comment]
Please note that PHP 5.3 and PHP 5.4 no longer receive security updates from the PHP team and both have been marked end of life for over a year now.
https://secure.php.net/eol.php
https://secure.php.net/supported-versions.php
