### ISSUE TITLE
breaks my wiki

### ISSUE THREAD

**Issue by davecotter** [Alexia/mediawiki-embedvideo#37]
when i paste this line in my LocalSettings:
 require_once( "$IP/extensions/EmbedVideo/EmbedVideo.php" );

my wiki pages simply fail to load, i get blank pages.   here's info on my wiki:
https://karaoke.kjams.com/wiki/Special:Version

any ideas

**Comment by Alexia** [comment]
You are running an outdated and insecure version of PHP, 5.3.26, from 2013.  The PHP 5.3 series was marked end of life in July 2013 and its last security patch was in August 2014.
https://secure.php.net/eol.php

You should upgrade to the PHP 5.4 series at a minimum to secure your web site and to support newer code.

P.S. Special:Version is broken on your wiki so I had to yank the information out of the API.

**Comment by davecotter** [comment]
> You are running an outdated and insecure version of PHP, 5.3.26, from 2013.
gosh, what a goof
okay fixing that

> P.S. Special:Version is broken on your wiki so I had to yank the information out of the API.
not sure what you mean by that.
when i go here:
https://karaoke.kjams.com/wiki/Special:Version

the page loads just fine.  what are you seeing?

**Comment by Alexia** [comment]
Special:Version is redirecting to Main_Page.  It might be because I am not logged into an account.

**Comment by davecotter** [comment]
oh, yeah, i guess so.
just tried it logged out, got same thing
