### ISSUE TITLE
syntax error, unexpected '['

### ISSUE THREAD

**Issue by bs135** [Alexia/mediawiki-embedvideo#39]
How to fix:
Parse error: syntax error, unexpected '[' in C:\inetpub\wwwroot\wiki\extensions\EmbedVideo\EmbedVideo.i18n.magic.php on line 12

**Comment by Alexia** [comment]
https://github.com/Alexia/mediawiki-embedvideo/issues/36
https://github.com/Alexia/mediawiki-embedvideo/issues/37
https://github.com/Alexia/mediawiki-embedvideo/issues/23
