### ISSUE TITLE
youtube-playlist not working

### ISSUE THREAD

**Issue by cadon** [Alexia/mediawiki-embedvideo#41]
When using for embedding a youtube-playlist, the iframe-src has a trailing '?' (questionmark-char) added, making the URI invalid.
I think I tracked the source of the '?' down to
classes/VideoService.php line 435
$data[] = '?'.$urlArgs;
guessing somewhere the urlArgs are set.

To reproduce insert into a mediawiki-page the text
`{{#ev:youtubeplaylist|https://www.youtube.com/playlist?list=PLOU2XLYxmsIIuCdpTAoeto25zjLNcPE4y}}`
and see the created html-code
`<iframe src="//www.youtube.com/embed/videoseries?list=PLOU2XLYxmsIIuCdpTAoeto25zjLNcPE4y?" allowfullscreen="true" frameborder="0" height="225" width="400"></iframe>`
note the extra '?' at the end of the list-id that makes the URI invalid.

**Comment by Alexia** [comment]
This was fixed by @chapatiyaq
https://github.com/Alexia/mediawiki-embedvideo/pull/40

I will be making a formal release this week.
